// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.0--rc3
// source: channel.proto

package godesk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChannelServiceClient is the client API for ChannelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChannelServiceClient interface {
	DataStream(ctx context.Context, opts ...grpc.CallOption) (ChannelService_DataStreamClient, error)
}

type channelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelServiceClient(cc grpc.ClientConnInterface) ChannelServiceClient {
	return &channelServiceClient{cc}
}

func (c *channelServiceClient) DataStream(ctx context.Context, opts ...grpc.CallOption) (ChannelService_DataStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChannelService_ServiceDesc.Streams[0], "/godesk.ChannelService/DataStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &channelServiceDataStreamClient{stream}
	return x, nil
}

type ChannelService_DataStreamClient interface {
	Send(*ChannelRequest) error
	Recv() (*ChannelRequest, error)
	grpc.ClientStream
}

type channelServiceDataStreamClient struct {
	grpc.ClientStream
}

func (x *channelServiceDataStreamClient) Send(m *ChannelRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *channelServiceDataStreamClient) Recv() (*ChannelRequest, error) {
	m := new(ChannelRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChannelServiceServer is the server API for ChannelService service.
// All implementations should embed UnimplementedChannelServiceServer
// for forward compatibility
type ChannelServiceServer interface {
	DataStream(ChannelService_DataStreamServer) error
}

// UnimplementedChannelServiceServer should be embedded to have forward compatible implementations.
type UnimplementedChannelServiceServer struct {
}

func (UnimplementedChannelServiceServer) DataStream(ChannelService_DataStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method DataStream not implemented")
}

// UnsafeChannelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelServiceServer will
// result in compilation errors.
type UnsafeChannelServiceServer interface {
	mustEmbedUnimplementedChannelServiceServer()
}

func RegisterChannelServiceServer(s grpc.ServiceRegistrar, srv ChannelServiceServer) {
	s.RegisterService(&ChannelService_ServiceDesc, srv)
}

func _ChannelService_DataStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChannelServiceServer).DataStream(&channelServiceDataStreamServer{stream})
}

type ChannelService_DataStreamServer interface {
	Send(*ChannelRequest) error
	Recv() (*ChannelRequest, error)
	grpc.ServerStream
}

type channelServiceDataStreamServer struct {
	grpc.ServerStream
}

func (x *channelServiceDataStreamServer) Send(m *ChannelRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *channelServiceDataStreamServer) Recv() (*ChannelRequest, error) {
	m := new(ChannelRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChannelService_ServiceDesc is the grpc.ServiceDesc for ChannelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChannelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "godesk.ChannelService",
	HandlerType: (*ChannelServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DataStream",
			Handler:       _ChannelService_DataStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "channel.proto",
}
