// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: channel.proto

package godesk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChannelRequest 双向数据流的基础消息
type ChannelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 发送方客户端唯一标识
	SendClientUuid string `protobuf:"bytes,1,opt,name=send_client_uuid,json=sendClientUuid,proto3" json:"send_client_uuid,omitempty"`
	// 目标客户端唯一标识
	TargetClientUuid string `protobuf:"bytes,2,opt,name=target_client_uuid,json=targetClientUuid,proto3" json:"target_client_uuid,omitempty"`
	// 数据类型（key 定义见下方注释）
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// 数据（JSON 格式，具体结构见各 key 的说明）
	Data          []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelRequest) Reset() {
	*x = ChannelRequest{}
	mi := &file_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRequest) ProtoMessage() {}

func (x *ChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRequest.ProtoReflect.Descriptor instead.
func (*ChannelRequest) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelRequest) GetSendClientUuid() string {
	if x != nil {
		return x.SendClientUuid
	}
	return ""
}

func (x *ChannelRequest) GetTargetClientUuid() string {
	if x != nil {
		return x.TargetClientUuid
	}
	return ""
}

func (x *ChannelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ChannelRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// RegisterData 设备注册数据（key = "register"）
type RegisterData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 操作系统：windows, darwin, linux
	Os string `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	// 设备名称
	DeviceName    string `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterData) Reset() {
	*x = RegisterData{}
	mi := &file_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterData) ProtoMessage() {}

func (x *RegisterData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterData.ProtoReflect.Descriptor instead.
func (*RegisterData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterData) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterData) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

// HeartbeatData 心跳数据（key = "heartbeat"）
type HeartbeatData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 时间戳（毫秒）
	Timestamp     int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatData) Reset() {
	*x = HeartbeatData{}
	mi := &file_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatData) ProtoMessage() {}

func (x *HeartbeatData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatData.ProtoReflect.Descriptor instead.
func (*HeartbeatData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ControlStartedRequestData 控制开始请求（控制端 = "control_started_request"）
type ControlStartedRequestData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 被控端设备码
	TargetCode uint64 `protobuf:"varint,1,opt,name=target_code,json=targetCode,proto3" json:"target_code,omitempty"`
	// 被控端密码
	TargetPassword string `protobuf:"bytes,2,opt,name=target_password,json=targetPassword,proto3" json:"target_password,omitempty"`
	// 是否请求完全控制权限（true=控制，false=仅查看）
	RequestControl bool `protobuf:"varint,3,opt,name=request_control,json=requestControl,proto3" json:"request_control,omitempty"`
	// 时间戳（毫秒）
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlStartedRequestData) Reset() {
	*x = ControlStartedRequestData{}
	mi := &file_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlStartedRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlStartedRequestData) ProtoMessage() {}

func (x *ControlStartedRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlStartedRequestData.ProtoReflect.Descriptor instead.
func (*ControlStartedRequestData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{3}
}

func (x *ControlStartedRequestData) GetTargetCode() uint64 {
	if x != nil {
		return x.TargetCode
	}
	return 0
}

func (x *ControlStartedRequestData) GetTargetPassword() string {
	if x != nil {
		return x.TargetPassword
	}
	return ""
}

func (x *ControlStartedRequestData) GetRequestControl() bool {
	if x != nil {
		return x.RequestControl
	}
	return false
}

func (x *ControlStartedRequestData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ControlStartedResponseData 控制开始响应（控制端 = "control_started_response"）
type ControlStartedResponseData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应码: 0=接受, 1=拒绝, 2=密码错误, 3=设备不存在, 4=设备离线
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 被控端唯一标识
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// 被控端设备码
	TargetCode    uint64 `protobuf:"varint,3,opt,name=target_code,json=targetCode,proto3" json:"target_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlStartedResponseData) Reset() {
	*x = ControlStartedResponseData{}
	mi := &file_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlStartedResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlStartedResponseData) ProtoMessage() {}

func (x *ControlStartedResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlStartedResponseData.ProtoReflect.Descriptor instead.
func (*ControlStartedResponseData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{4}
}

func (x *ControlStartedResponseData) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ControlStartedResponseData) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ControlStartedResponseData) GetTargetCode() uint64 {
	if x != nil {
		return x.TargetCode
	}
	return 0
}

// ControlEndedRequestData 控制结束通知数据（key = "control_ended_request"）
type ControlEndedRequestData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 被控端设备码
	TargetCode uint64 `protobuf:"varint,1,opt,name=target_code,json=targetCode,proto3" json:"target_code,omitempty"`
	// 时间戳（毫秒）
	Timestamp     int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlEndedRequestData) Reset() {
	*x = ControlEndedRequestData{}
	mi := &file_channel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlEndedRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlEndedRequestData) ProtoMessage() {}

func (x *ControlEndedRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlEndedRequestData.ProtoReflect.Descriptor instead.
func (*ControlEndedRequestData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{5}
}

func (x *ControlEndedRequestData) GetTargetCode() uint64 {
	if x != nil {
		return x.TargetCode
	}
	return 0
}

func (x *ControlEndedRequestData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ControlEndedResponseData 控制结束通知数据（key = "control_ended_response"）
type ControlEndedResponseData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应码: 0=成功, 1=失败
	Code          int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlEndedResponseData) Reset() {
	*x = ControlEndedResponseData{}
	mi := &file_channel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlEndedResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlEndedResponseData) ProtoMessage() {}

func (x *ControlEndedResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlEndedResponseData.ProtoReflect.Descriptor instead.
func (*ControlEndedResponseData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{6}
}

func (x *ControlEndedResponseData) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// ScreenStreamData 屏幕流数据（key = "screen_stream_data"）
type ScreenStreamData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 图像数据（Base64 编码的 JPEG/PNG 图片）
	ImageData string `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	// 图片格式：jpeg, png
	Format string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	// 图片宽度（像素）
	Width int32 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	// 图片高度（像素）
	Height int32 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	// 时间戳（毫秒）
	Timestamp     int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenStreamData) Reset() {
	*x = ScreenStreamData{}
	mi := &file_channel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenStreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenStreamData) ProtoMessage() {}

func (x *ScreenStreamData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenStreamData.ProtoReflect.Descriptor instead.
func (*ScreenStreamData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{7}
}

func (x *ScreenStreamData) GetImageData() string {
	if x != nil {
		return x.ImageData
	}
	return ""
}

func (x *ScreenStreamData) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ScreenStreamData) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ScreenStreamData) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ScreenStreamData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// MouseMoveData 鼠标移动数据（key = "mouse_move"）
type MouseMoveData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// X 坐标（像素）
	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	// Y 坐标（像素）
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	// 时间戳（毫秒）
	Timestamp     int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MouseMoveData) Reset() {
	*x = MouseMoveData{}
	mi := &file_channel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MouseMoveData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MouseMoveData) ProtoMessage() {}

func (x *MouseMoveData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MouseMoveData.ProtoReflect.Descriptor instead.
func (*MouseMoveData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{8}
}

func (x *MouseMoveData) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MouseMoveData) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MouseMoveData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// MouseClickData 鼠标点击数据（key = "mouse_click"）
type MouseClickData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// X 坐标（像素）
	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	// Y 坐标（像素）
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	// 鼠标按钮：0=左键, 1=右键, 2=中键
	Button int32 `protobuf:"varint,3,opt,name=button,proto3" json:"button,omitempty"`
	// 动作：down=按下, up=释放
	Action string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	// 时间戳（毫秒）
	Timestamp     int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MouseClickData) Reset() {
	*x = MouseClickData{}
	mi := &file_channel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MouseClickData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MouseClickData) ProtoMessage() {}

func (x *MouseClickData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MouseClickData.ProtoReflect.Descriptor instead.
func (*MouseClickData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{9}
}

func (x *MouseClickData) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MouseClickData) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MouseClickData) GetButton() int32 {
	if x != nil {
		return x.Button
	}
	return 0
}

func (x *MouseClickData) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MouseClickData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// MouseScrollData 鼠标滚轮数据（key = "mouse_scroll"）
type MouseScrollData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// X 坐标（像素）
	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	// Y 坐标（像素）
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	// 垂直滚动量（正值向下，负值向上）
	DeltaY int32 `protobuf:"varint,3,opt,name=delta_y,json=deltaY,proto3" json:"delta_y,omitempty"`
	// 时间戳（毫秒）
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MouseScrollData) Reset() {
	*x = MouseScrollData{}
	mi := &file_channel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MouseScrollData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MouseScrollData) ProtoMessage() {}

func (x *MouseScrollData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MouseScrollData.ProtoReflect.Descriptor instead.
func (*MouseScrollData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{10}
}

func (x *MouseScrollData) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MouseScrollData) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MouseScrollData) GetDeltaY() int32 {
	if x != nil {
		return x.DeltaY
	}
	return 0
}

func (x *MouseScrollData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// KeyTapData 键盘按键数据（key = "key_tap"）
type KeyTapData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 按键名称（小写，如 "a", "enter", "ctrl" 等）
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// 修饰键列表（可选），如 ["ctrl", "shift"]
	Modifiers []string `protobuf:"bytes,2,rep,name=modifiers,proto3" json:"modifiers,omitempty"`
	// 时间戳（毫秒）
	Timestamp     int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyTapData) Reset() {
	*x = KeyTapData{}
	mi := &file_channel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyTapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyTapData) ProtoMessage() {}

func (x *KeyTapData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyTapData.ProtoReflect.Descriptor instead.
func (*KeyTapData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{11}
}

func (x *KeyTapData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyTapData) GetModifiers() []string {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

func (x *KeyTapData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// KeyDownData 键盘按下数据（key = "key_down"）
type KeyDownData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 按键名称（小写）
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// 修饰键列表（可选）
	Modifiers []string `protobuf:"bytes,2,rep,name=modifiers,proto3" json:"modifiers,omitempty"`
	// 时间戳（毫秒）
	Timestamp     int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyDownData) Reset() {
	*x = KeyDownData{}
	mi := &file_channel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyDownData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyDownData) ProtoMessage() {}

func (x *KeyDownData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyDownData.ProtoReflect.Descriptor instead.
func (*KeyDownData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{12}
}

func (x *KeyDownData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyDownData) GetModifiers() []string {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

func (x *KeyDownData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// KeyUpData 键盘释放数据（key = "key_up"）
type KeyUpData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 按键名称（小写）
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// 修饰键列表（可选）
	Modifiers []string `protobuf:"bytes,2,rep,name=modifiers,proto3" json:"modifiers,omitempty"`
	// 时间戳（毫秒）
	Timestamp     int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyUpData) Reset() {
	*x = KeyUpData{}
	mi := &file_channel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyUpData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyUpData) ProtoMessage() {}

func (x *KeyUpData) ProtoReflect() protoreflect.Message {
	mi := &file_channel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyUpData.ProtoReflect.Descriptor instead.
func (*KeyUpData) Descriptor() ([]byte, []int) {
	return file_channel_proto_rawDescGZIP(), []int{13}
}

func (x *KeyUpData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyUpData) GetModifiers() []string {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

func (x *KeyUpData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_channel_proto protoreflect.FileDescriptor

const file_channel_proto_rawDesc = "" +
	"\n" +
	"\rchannel.proto\x12\x06godesk\"\x8e\x01\n" +
	"\x0eChannelRequest\x12(\n" +
	"\x10send_client_uuid\x18\x01 \x01(\tR\x0esendClientUuid\x12,\n" +
	"\x12target_client_uuid\x18\x02 \x01(\tR\x10targetClientUuid\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"?\n" +
	"\fRegisterData\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\"-\n" +
	"\rHeartbeatData\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xac\x01\n" +
	"\x19ControlStartedRequestData\x12\x1f\n" +
	"\vtarget_code\x18\x01 \x01(\x04R\n" +
	"targetCode\x12'\n" +
	"\x0ftarget_password\x18\x02 \x01(\tR\x0etargetPassword\x12'\n" +
	"\x0frequest_control\x18\x03 \x01(\bR\x0erequestControl\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"e\n" +
	"\x1aControlStartedResponseData\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vtarget_code\x18\x03 \x01(\x04R\n" +
	"targetCode\"X\n" +
	"\x17ControlEndedRequestData\x12\x1f\n" +
	"\vtarget_code\x18\x01 \x01(\x04R\n" +
	"targetCode\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\".\n" +
	"\x18ControlEndedResponseData\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\"\x95\x01\n" +
	"\x10ScreenStreamData\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\tR\timageData\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"I\n" +
	"\rMouseMoveData\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"z\n" +
	"\x0eMouseClickData\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x16\n" +
	"\x06button\x18\x03 \x01(\x05R\x06button\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"d\n" +
	"\x0fMouseScrollData\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x17\n" +
	"\adelta_y\x18\x03 \x01(\x05R\x06deltaY\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"Z\n" +
	"\n" +
	"KeyTapData\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tmodifiers\x18\x02 \x03(\tR\tmodifiers\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"[\n" +
	"\vKeyDownData\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tmodifiers\x18\x02 \x03(\tR\tmodifiers\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"Y\n" +
	"\tKeyUpData\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tmodifiers\x18\x02 \x03(\tR\tmodifiers\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2T\n" +
	"\x0eChannelService\x12B\n" +
	"\n" +
	"DataStream\x12\x16.godesk.ChannelRequest\x1a\x16.godesk.ChannelRequest\"\x00(\x010\x01B\vZ\t./;godeskb\x06proto3"

var (
	file_channel_proto_rawDescOnce sync.Once
	file_channel_proto_rawDescData []byte
)

func file_channel_proto_rawDescGZIP() []byte {
	file_channel_proto_rawDescOnce.Do(func() {
		file_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_channel_proto_rawDesc), len(file_channel_proto_rawDesc)))
	})
	return file_channel_proto_rawDescData
}

var file_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_channel_proto_goTypes = []any{
	(*ChannelRequest)(nil),             // 0: godesk.ChannelRequest
	(*RegisterData)(nil),               // 1: godesk.RegisterData
	(*HeartbeatData)(nil),              // 2: godesk.HeartbeatData
	(*ControlStartedRequestData)(nil),  // 3: godesk.ControlStartedRequestData
	(*ControlStartedResponseData)(nil), // 4: godesk.ControlStartedResponseData
	(*ControlEndedRequestData)(nil),    // 5: godesk.ControlEndedRequestData
	(*ControlEndedResponseData)(nil),   // 6: godesk.ControlEndedResponseData
	(*ScreenStreamData)(nil),           // 7: godesk.ScreenStreamData
	(*MouseMoveData)(nil),              // 8: godesk.MouseMoveData
	(*MouseClickData)(nil),             // 9: godesk.MouseClickData
	(*MouseScrollData)(nil),            // 10: godesk.MouseScrollData
	(*KeyTapData)(nil),                 // 11: godesk.KeyTapData
	(*KeyDownData)(nil),                // 12: godesk.KeyDownData
	(*KeyUpData)(nil),                  // 13: godesk.KeyUpData
}
var file_channel_proto_depIdxs = []int32{
	0, // 0: godesk.ChannelService.DataStream:input_type -> godesk.ChannelRequest
	0, // 1: godesk.ChannelService.DataStream:output_type -> godesk.ChannelRequest
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_channel_proto_init() }
func file_channel_proto_init() {
	if File_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_channel_proto_rawDesc), len(file_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_channel_proto_goTypes,
		DependencyIndexes: file_channel_proto_depIdxs,
		MessageInfos:      file_channel_proto_msgTypes,
	}.Build()
	File_channel_proto = out.File
	file_channel_proto_goTypes = nil
	file_channel_proto_depIdxs = nil
}
