// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.0--rc3
// source: device_basic.proto

package godesk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 设备唯一标识
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfoRequest) Reset() {
	*x = DeviceInfoRequest{}
	mi := &file_device_basic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoRequest) ProtoMessage() {}

func (x *DeviceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_basic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoRequest.ProtoReflect.Descriptor instead.
func (*DeviceInfoRequest) Descriptor() ([]byte, []int) {
	return file_device_basic_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfoRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeviceInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 设备唯一标识
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// 设备码
	Code uint64 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	// 操作系统, win, mac, linux
	Os            string `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfoResponse) Reset() {
	*x = DeviceInfoResponse{}
	mi := &file_device_basic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoResponse) ProtoMessage() {}

func (x *DeviceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_basic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoResponse.ProtoReflect.Descriptor instead.
func (*DeviceInfoResponse) Descriptor() ([]byte, []int) {
	return file_device_basic_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceInfoResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DeviceInfoResponse) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeviceInfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

type CreateDeviceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 操作系统
	Os            string `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeviceRequest) Reset() {
	*x = CreateDeviceRequest{}
	mi := &file_device_basic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceRequest) ProtoMessage() {}

func (x *CreateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_basic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceRequest.ProtoReflect.Descriptor instead.
func (*CreateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_device_basic_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDeviceRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

var File_device_basic_proto protoreflect.FileDescriptor

const file_device_basic_proto_rawDesc = "" +
	"\n" +
	"\x12device_basic.proto\x12\x06godesk\"'\n" +
	"\x11DeviceInfoRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"L\n" +
	"\x12DeviceInfoResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x04R\x04code\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\"%\n" +
	"\x13CreateDeviceRequest\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os2\xa4\x01\n" +
	"\rDeviceService\x12H\n" +
	"\rGetDeviceInfo\x12\x19.godesk.DeviceInfoRequest\x1a\x1a.godesk.DeviceInfoResponse\"\x00\x12I\n" +
	"\fCreateDevice\x12\x1b.godesk.CreateDeviceRequest\x1a\x1a.godesk.DeviceInfoResponse\"\x00B\vZ\t./;godeskb\x06proto3"

var (
	file_device_basic_proto_rawDescOnce sync.Once
	file_device_basic_proto_rawDescData []byte
)

func file_device_basic_proto_rawDescGZIP() []byte {
	file_device_basic_proto_rawDescOnce.Do(func() {
		file_device_basic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_device_basic_proto_rawDesc), len(file_device_basic_proto_rawDesc)))
	})
	return file_device_basic_proto_rawDescData
}

var file_device_basic_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_device_basic_proto_goTypes = []any{
	(*DeviceInfoRequest)(nil),   // 0: godesk.DeviceInfoRequest
	(*DeviceInfoResponse)(nil),  // 1: godesk.DeviceInfoResponse
	(*CreateDeviceRequest)(nil), // 2: godesk.CreateDeviceRequest
}
var file_device_basic_proto_depIdxs = []int32{
	0, // 0: godesk.DeviceService.GetDeviceInfo:input_type -> godesk.DeviceInfoRequest
	2, // 1: godesk.DeviceService.CreateDevice:input_type -> godesk.CreateDeviceRequest
	1, // 2: godesk.DeviceService.GetDeviceInfo:output_type -> godesk.DeviceInfoResponse
	1, // 3: godesk.DeviceService.CreateDevice:output_type -> godesk.DeviceInfoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_device_basic_proto_init() }
func file_device_basic_proto_init() {
	if File_device_basic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_device_basic_proto_rawDesc), len(file_device_basic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_basic_proto_goTypes,
		DependencyIndexes: file_device_basic_proto_depIdxs,
		MessageInfos:      file_device_basic_proto_msgTypes,
	}.Build()
	File_device_basic_proto = out.File
	file_device_basic_proto_goTypes = nil
	file_device_basic_proto_depIdxs = nil
}
